// services/report-builder.service.js — Enterprise HTML Report Builder
// Converts structured JSON (AI output + risk scores) into professional HTML

const path = require('path');
const fs = require('fs');
const logger = require('../../../utils/logger.utils');

/* ===============================
   SEVERITY COLORS
   =============================== */

const SEVERITY_COLORS = {
    Critical: { bg: '#dc2626', text: '#fff', border: '#b91c1c', light: '#fef2f2' },
    High: { bg: '#ea580c', text: '#fff', border: '#c2410c', light: '#fff7ed' },
    Medium: { bg: '#d97706', text: '#fff', border: '#b45309', light: '#fffbeb' },
    Low: { bg: '#2563eb', text: '#fff', border: '#1d4ed8', light: '#eff6ff' }
};

const PRIORITY_COLORS = {
    P0: '#dc2626',
    P1: '#ea580c',
    P2: '#d97706',
    P3: '#2563eb'
};

const POSTURE_COLORS = {
    'Critical': '#dc2626',
    'High Risk': '#ea580c',
    'Moderate': '#d97706',
    'Good': '#16a34a',
    'Excellent': '#059669'
};

/* ===============================
   HELPER FUNCTIONS
   =============================== */

const escapeHtml = (str) => {
    if (typeof str !== 'string') return String(str || '');
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
};

const getCompanyName = (targetUrl) => {
    try {
        const urlObj = new URL(targetUrl);
        const hostname = urlObj.hostname.replace(/^www\./, '');
        const parts = hostname.split('.');
        return parts.length >= 2 ? parts.slice(0, -1).join('.') : hostname;
    } catch {
        return targetUrl.replace(/[^a-z0-9]/gi, '_');
    }
};

/* ===============================
   CACHED LOGOS (loaded once at startup)
   =============================== */

let _cachedLogoLeft = '';
let _cachedLogoRight = '';
try {
    _cachedLogoLeft = `data:image/png;base64,${fs.readFileSync(path.join(__dirname, '../../reports/logo-fcis.png')).toString('base64')}`;
} catch { }
try {
    _cachedLogoRight = `data:image/png;base64,${fs.readFileSync(path.join(__dirname, '../../reports/logo-october.png')).toString('base64')}`;
} catch { }

/* ===============================
   SECTION BUILDERS
   =============================== */

   const buildCoverAndSummary = (aiReport, metadata, targetUrl) => {
    const companyName = getCompanyName(targetUrl); // 
    const exec = aiReport.executiveSummary || {}; // 
    const findingsCount = (aiReport.findings || []).length; // 
    
    // تحديد لون حالة الأمان بناءً على التصنيف
    const postureClass = metadata.securityPosture?.classification || 'Pending'; // 
    
    return `
    <div class="logo-container">
        <img src="${_cachedLogoLeft}" alt="Left Logo">
        <img src="${_cachedLogoRight}" alt="Right Logo">
    </div>

    <div class="header-banner">
        <h1>🔒 PENETRATION TESTING REPORT</h1>
        <p><strong>Client:</strong> ${escapeHtml(companyName)}</p>
        <p><strong>Target:</strong> ${escapeHtml(targetUrl)}</p>
        <p><strong>Generated:</strong> ${new Date(metadata.generatedAt).toLocaleString('en-US')}</p>
        <p><strong>Classification:</strong> ${escapeHtml(metadata.classification)}</p>
    </div>

    <div class="posture-card">
        <div class="posture-label">Overall Security Posture</div>
        <div class="posture-status">${escapeHtml(postureClass)}</div>
        <div class="posture-score">Security Score: ${metadata.securityPosture?.score || 0}/100</div>
    </div>
    
    <h2 class="section-title">DOCUMENT INFORMATION</h2>
    <table class="info-table">
        <tr><td class="info-label">Report Type</td><td>Evidence-Based Security Assessment</td></tr>
        <tr><td class="info-label">Target</td><td>${escapeHtml(targetUrl)}</td></tr>
        <tr><td class="info-label">Assessment Date</td><td>${new Date(metadata.generatedAt).toISOString().split('T')[0]}</td></tr>
        <tr><td class="info-label">Total Findings</td><td>${findingsCount}</td></tr>
        <tr><td class="info-label">Generated By</td><td>VulnCraft AI</td></tr>
    </table>

    <h2 class="section-title">1. EXECUTIVE SUMMARY</h2>
    <h3>1.1 Assessment Overview</h3>
    <p>${escapeHtml(exec.assessmentOverview || 'No overview available.')}</p>
    
    <h3>1.2 Key Observations</h3>
    <p>${escapeHtml(exec.keyObservations || 'No key observations available.')}</p>
    `;
};

const buildAssessmentContext = (aiReport, metadata, targetUrl) => {
    return `
    <h2 class="section-title">2. ASSESSMENT CONTEXT</h2>
    <p><strong>Target Application:</strong> ${escapeHtml(targetUrl)}</p>
    <p><strong>Assessment Type:</strong> Black Box</p>
    <p><strong>Assessment Nature:</strong> Automated testing with evidence-based review</p>
    <p><strong>Methodology Reference:</strong> OWASP Testing Guide, PTES</p>
    `;
};

// --- تعديل قسم النتائج (بدون Parameter/Payload) ---
const buildFindingsSection = (aiReport, enrichedFindings) => {
    const findings = aiReport.findings || [];
    if (findings.length === 0) return '';

    let html = `<div class="page-break-before"></div><h2 class="section-title">3. OBSERVED SECURITY FINDINGS</h2>`;

    findings.forEach(finding => {
        const evidence = finding.technicalEvidence && finding.technicalEvidence[0] ? finding.technicalEvidence[0] : {};

        html += `
        <div class="finding-block">
            <h3 class="finding-header-title">${escapeHtml(finding.id)} - ${escapeHtml(finding.title)}</h3>
            <p><strong>Severity:</strong> <span class="badge bg-${finding.severity?.toLowerCase()}">${escapeHtml(finding.severity)}</span></p>
            
            ${finding.observationSummary ? `
                <h4 class="finding-subtitle">Observation Summary</h4>
                <p>${escapeHtml(finding.observationSummary)}</p>` : ''}
            
            ${finding.whyThisMatters ? `
                <h4 class="finding-subtitle">Why This Matters</h4>
                <p>${escapeHtml(finding.whyThisMatters)}</p>` : ''}
            
            <h4 class="finding-subtitle">Technical Evidence</h4>
            <p><strong>Endpoint:</strong> ${escapeHtml(evidence.endpoint || 'N/A')}</p>
            <p><strong>Observed Behavior:</strong> ${escapeHtml(evidence.observedResponse || 'Manual validation required')}</p>        
        </div>`;
    });
    return html;
};

const buildFindingsSummary = (aiReport) => {
    const findings = aiReport.findings || [];
    if (findings.length === 0) return '';

    let html = `
    <div class="page-break-before"></div>
    <h2 class="section-title">4. FINDINGS SUMMARY</h2>
    <table class="summary-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Severity</th>
                <th>Evidence Confidence</th>
            </tr>
        </thead>
        <tbody>`;

    findings.forEach(finding => {
        html += `
            <tr>
                <td>${escapeHtml(finding.id)}</td>
                <td>${escapeHtml(finding.title)}</td>
                <td>${escapeHtml(finding.severity)}</td>
                <td>${escapeHtml(finding.evidenceConfidence || 'Medium')}</td>
            </tr>`;
    });

    html += `</tbody></table>`;
    return html;
};

const buildRemediationGuidance = (aiReport) => {
    const findings = aiReport.findings || [];
    if (findings.length === 0) return '';

    let html = `<div class="page-break-before"></div><h2 class="section-title">5. REMEDIATION & VALIDATION GUIDANCE</h2>`;

    findings.forEach(finding => {
        const rem = finding.remediation || {};
        html += `
        <div class="remediation-block">
            <h3 class="finding-header-title">${escapeHtml(finding.id)} - ${escapeHtml(finding.title)}</h3>
            
            <h4 class="finding-subtitle">Strategic Recommendation</h4>
            <p>${escapeHtml(rem.recommendation || finding.remediationGuidance || 'No guidance provided.')}</p>
            
            ${rem.technicalFix ? `
                <h4 class="finding-subtitle">Technical Implementation (Code Fix)</h4>
                <pre><code>${escapeHtml(rem.technicalFix)}</code></pre>` : ''}
            
            ${rem.verificationSteps ? `
                <h4 class="finding-subtitle">Validation & Verification Steps</h4>
                <p>${escapeHtml(rem.verificationSteps).replace(/\n/g, '<br>')}</p>` : ''}
                
            <p style="margin-top:10px;"><strong>References:</strong> ${escapeHtml((rem.references || []).join(', '))}</p>
        </div>`;
    });
    return html;
};

const buildVerdict = (aiReport) => {
    return `
    <h2 class="section-title">6. OVERALL ASSESSMENT VERDICT</h2>
    <p>${escapeHtml(aiReport.overallAssessmentVerdict || 'No significant security issues detected. Continue monitoring and periodic assessment as part of the security program.')}</p>
    `;
};

const buildTechnicalAppendix = (aiReport) => {
    const findings = aiReport.findings || [];
    if (findings.length === 0) return '';

    let html = `
    <div class="page-break-before"></div>
    <h2 class="section-title">7. TECHNICAL APPENDIX</h2>`;

    findings.forEach(finding => {
        const evidence = finding.technicalEvidence && finding.technicalEvidence[0] ? finding.technicalEvidence[0] : {};
        html += `
        <div class="appendix-block">
            <h3 class="finding-header-title">${escapeHtml(finding.id)} - ${escapeHtml(finding.title)}</h3>
            <p><strong>Finding ID:</strong> ${escapeHtml(finding.id)}</p>
            <p><strong>Endpoint(s):</strong> ${escapeHtml(evidence.endpoint || 'N/A')}</p>
            <p><strong>Observed response patterns:</strong> ${escapeHtml(evidence.observedResponse || 'N/A')}</p>
        </div>`;
    });
    
    html += `<div class="end-of-report"><p><strong>END OF REPORT</strong></p></div>`;
    return html;
};
/* ===============================
   MAIN EXPORT
   =============================== */

const crossValidateFindings = (aiReport, enrichedFindings) => {
    return aiReport; // Trust AI consolidation as planned
};

exports.buildFullReportHTML = (aiReport, metadata, enrichedFindings) => {
    try {
        const targetUrl = metadata.targetUrl || 'Unknown Target';
        
        // Cross-validate: remove any AI-hallucinated findings (currently a passthrough)
        aiReport = crossValidateFindings(aiReport, enrichedFindings);

        const hasFindings = aiReport.findings && aiReport.findings.length > 0;

        // Load CSS
        const cssPath = path.join(__dirname, '../../reports/report.css');
        let css = '';
        try { css = fs.readFileSync(cssPath, 'utf8'); } catch { }

        const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Security Assessment Report — ${escapeHtml(targetUrl)}</title>
<style>${css}</style>
</head>
<body>
${buildCoverAndSummary(aiReport, metadata, targetUrl)}
${buildAssessmentContext(aiReport, metadata, targetUrl)}
${hasFindings ? buildRiskMatrix(metadata) : ''}
${hasFindings ? buildFindingsSection(aiReport, enrichedFindings) : ''}
${hasFindings ? buildFindingsSummary(aiReport) : ''}
${hasFindings ? buildRemediationGuidance(aiReport) : ''}
${hasFindings ? buildStrategicRecommendations(aiReport) : ''}
${hasFindings ? buildProgramImprovements(aiReport) : ''}
${buildVerdict(aiReport)}
${hasFindings ? buildTechnicalAppendix(aiReport) : ''}
<div class="footer-note">VulnCraft – Security Assessment Project CONFIDENTIAL</div>
</body>
</html>`;

        logger?.info('✅ Minimalist Report HTML built successfully');
        return html;

    } catch (error) {
        logger?.error(`❌ Report builder error: ${error.message}`);
        throw error;
    }
};

const buildRiskMatrix = (metadata) => {
    const matrix = metadata.riskMatrix || {};
    return `
    <div class="page-break-before"></div>
    <h2 class="section-title">3. RISK OVERVIEW</h2>
    <h3>3.1 Risk Heatmap (Impact x Likelihood)</h3>
    <table class="summary-table" style="text-align: center;">
        <thead>
            <tr>
                <th>IMPACT / LIKELIHOOD</th>
                <th style="background: #fee2e2;">HIGH</th>
                <th style="background: #fef3c7;">MEDIUM</th>
                <th style="background: #eff6ff;">LOW</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="font-weight: bold; background: #f8fafc;">Critical</td>
                <td style="color: #dc2626; font-weight: bold;">${matrix.Critical?.High?.join(', ') || '-'}</td>
                <td style="color: #ea580c;">${matrix.Critical?.Medium?.join(', ') || '-'}</td>
                <td>-</td>
            </tr>
            <tr>
                <td style="font-weight: bold; background: #f8fafc;">High</td>
                <td style="color: #ea580c; font-weight: bold;">${matrix.High?.High?.join(', ') || '-'}</td>
                <td style="color: #d97706;">${matrix.High?.Medium?.join(', ') || '-'}</td>
                <td>-</td>
            </tr>
            <tr>
                <td style="font-weight: bold; background: #f8fafc;">Medium / Low</td>
                <td style="color: #d97706;">${matrix.Medium?.High?.join(', ') || '-'}</td>
                <td>${[...(matrix.Medium?.Medium || []), ...(matrix.Low?.Medium || [])].join(', ') || '-'}</td>
                <td style="color: #2563eb;">${matrix.Low?.Low?.join(', ') || '-'}</td>
            </tr>
        </tbody>
    </table>`;
};

// وظيفة لتحويل تفاصيل السكنر لبيانات مفهومة للـ AI
/**
 * بتحول تفاصيل السكنر الخام لبيانات مفهومة للتقرير والذكاء الاصطناعي
 */
const mapScannerDetailToEvidence = (vulnerability) => {
    const detail = vulnerability.technicalDetail || {};
    const info = [];

    // 1. فحص الهيدرز المكشوفة
    if (detail.disclosed_headers && detail.disclosed_headers.length > 0) {
        info.push(`Exposed Headers detected: ${detail.disclosed_headers.join(', ')}`);
    }

    // 2. فحص الهيدرز الأمنية الناقصة
    if (detail.missing_headers && detail.missing_headers.length > 0) {
        info.push(`Security Hardening Gap: Missing [${detail.missing_headers.join(', ')}]`);
    }

    // 3. فحص الـ Permissions Policy
    if (detail.check_name === "Permissions Policy" && detail.present === false) {
        info.push("Permissions-Policy header is completely absent from the server response.");
    }

    // 4. فحص مشاكل التشفير (TLS/SSL)
    if (detail.check_name === "TLS Security") {
        if (detail.https_used === false) {
            info.push("Critical: Application is served over plaintext HTTP (No HTTPS).");
        }
        if (detail.reason) {
            info.push(`Encryption Failure Reason: ${detail.reason}`);
        }
    }

    // 5. فحص أخطاء الـ Python (لو السكنر كراش)
    if (detail.pythonError) {
        info.push(`Scanner internal error: ${detail.pythonError.split('\n')[0]}`);
    }

    // لو ملقيناش حاجة نرجع النص الافتراضي
    return info.length > 0 ? info.join(' | ') : "Indicators suggest configuration weakness; manual verification required.";
};


const buildStrategicRecommendations = (aiReport) => {
    const recs = aiReport.strategicRecommendations || [];
    if (recs.length === 0) return '';

    let html = `<div class="page-break-before"></div><h2 class="section-title">6. STRATEGIC RECOMMENDATIONS</h2>`;
    recs.forEach(rec => {
        html += `
        <div class="remediation-block">
            <h3>${escapeHtml(rec.area)} <span class="effort-badge">Effort: ${escapeHtml(rec.estimatedEffort)}</span></h3>
            <p><strong>Recommendation:</strong> ${escapeHtml(rec.recommendation)}</p>
            <p><strong>Business Benefit:</strong> ${escapeHtml(rec.businessBenefit)}</p>
            <p><strong>Tools Required:</strong> ${escapeHtml(rec.toolsRequired || 'N/A')}</p>
        </div>`;
    });
    return html;
};

const buildProgramImprovements = (aiReport) => {
    const items = aiReport.securityProgramImprovements || [];
    if (items.length === 0) return '';

    let html = `<h2 class="section-title">7. SECURITY PROGRAM IMPROVEMENTS</h2>
    <table class="summary-table">
        <thead><tr><th>Phase</th><th>Initiative</th><th>Expected Outcome</th></tr></thead>
        <tbody>`;
    items.forEach(item => {
        html += `<tr>
            <td><strong>${escapeHtml(item.phase)}</strong></td>
            <td>${escapeHtml(item.initiative)}</td>
            <td>${escapeHtml(item.expectedOutcome)}</td>
        </tr>`;
    });
    html += `</tbody></table>`;
    return html;
};

exports.getCompanyName = getCompanyName;
// أضف هذا السطر في نهاية الملف مع الـ exports الأخرى
exports.mapScannerDetailToEvidence = mapScannerDetailToEvidence;